export const errors = {
  PROJECT_NOT_FOUND: {
    message: "Project not found",
    code: 404,
    errorCode: "PROJECT_NOT_FOUND",
    suggestion: "Please check the existence of the project.",
  },
  PROJECT_EXISTS: {
    message: "A project with the same name already exists",
    code: 409,
    errorCode: "PROJECT_EXISTS",
    suggestion: "Please choose a different name for the project.",
  },
  PROJECT_ID_REQUIRED: {
    message: "Project ID is required",
    code: 400,
    errorCode: "PROJECT_ID_REQUIRED",
    suggestion: "Please provide a valid project ID.",
  },
  ARCHIVED_PROJECT: {
    message: "Cannot perform this action on an archived project",
    code: 400,
    errorCode: "ARCHIVED_PROJECT",
    suggestion: "Please unarchive the project to perform this action.",
  },
  ON_HOLD_PROJECT: {
    message: "Cannot perform this action on an on-hold project",
    code: 400,
    errorCode: "ON_HOLD_PROJECT",
    suggestion: "Please resume the project to perform this action.",
  },
  COMPLETED_PROJECT: {
    message: "Cannot perform this action on a completed project",
    code: 400,
    errorCode: "COMPLETED_PROJECT",
    suggestion: "Please reopen the project to perform this action.",
  },
  UNAUTHORIZED_TO_ACCESS_PROJECT: {
    message: "Unauthorized to access the project",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_ACCESS_PROJECT",
    suggestion: "You do not have permission to access this project.",
  },
  MISSING_REQUIRED_FIELDS: {
    message: "Missing required fields",
    code: 400,
    errorCode: "MISSING_REQUIRED_FIELDS",
    suggestion: "Please provide all required fields.",
  },
  INVALID_SECTOR: {
    message: "Invalid sector",
    code: 400,
    errorCode: "INVALID_SECTOR",
    suggestion: "Please choose a valid sector for the project.",
  },
  INVALID_STATUS: {
    message: "Invalid status",
    code: 400,
    errorCode: "INVALID_STATUS",
    suggestion: "Please choose a valid status for the project.",
  },
  INVALID_DUE_DATE: {
    message: "Invalid due date",
    code: 400,
    errorCode: "INVALID_DUE_DATE",
    suggestion: "Due date must be after the start date.",
  },
  UNAUTHORIZED_TO_ASSIGN_SCRUM_MASTER: {
    message: "Unauthorized to assign the scrum master",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_ASSIGN_SCRUM_MASTER",
    suggestion: "The scrum master must be under the same product owner's team.",
  },
  INVALID_SCRUM_MASTER: {
    message: "Invalid scrum master",
    code: 400,
    errorCode: "INVALID_SCRUM_MASTER",
    suggestion: "The scrum master cannot be an intern.",
  },
  DUPLICATE_USERS: {
    message: "Duplicate users in the team",
    code: 400,
    errorCode: "DUPLICATE_USERS",
    suggestion: "Please remove duplicate users from the team members list.",
  },
  UNAUTHORIZED_TO_ADD_TEAM_MEMBER: {
    message: "Unauthorized to add team member",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_ADD_TEAM_MEMBER",
    suggestion: "Team members must be under the same product owner's team.",
  },
  MORE_THAN_ONE_SCRUM_MASTER: {
    message: "More than one scrum master in the team members",
    code: 400,
    errorCode: "MORE_THAN_ONE_SCRUM_MASTER",
    suggestion: "Only one scrum master can be assigned to the project.",
  },
  UNAUTHORIZED_TO_UPDATE_PROJECT :{
    message: "Unauthorized to update the project",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_UPDATE_PROJECT",
    suggestion: "Only the product owner can update the project.",
  },
  LOCKED_PROJECT: {
    message: "The project is locked due to its completed or on-hold status",
    code: 400,
    errorCode: "LOCKED_PROJECT",
    suggestion: "Please change the status of the project to unlock further functionalities.",
  },
  ON_HOLD_REASON_NOT_ALLOWED: {
    message: "On hold reason is only allowed when the project status is set to on hold",
    code: 400,
    errorCode: "ON_HOLD_REASON_NOT_ALLOWED",
    suggestion: "Please set the project status to 'On Hold' to provide a hold reason.",
  },
  TEAM_NOT_FOUND: {
    message: "Team not found",
    code: 404,
    errorCode: "TEAM_NOT_FOUND",
    suggestion: "Please check the existence of the team linked to the project.",
  },
  SCRUM_MASTER_REQUIRED: {
    message: "Scrum master is required when the project status is set to active",
    code: 400,
    errorCode: "SCRUM_MASTER_REQUIRED",
    suggestion: "Please assign a scrum master to the project to set it as active.",
  },
  TEAM_MEMBERS_REQUIRED: {
    message: "At least one team member is required when the project status is set to active",
    code: 400,
    errorCode: "TEAM_MEMBERS_REQUIRED",
    suggestion: "Please assign at least one team member to the project to set it as active.",
  },
  UNAUTHORIZED_TO_ARCHIVE_PROJECT: {
    message: "Unauthorized to archive the project",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_ARCHIVE_PROJECT",
    suggestion: "Only the product owner can archive the project.",
  },
  PROJECT_ALREADY_ARCHIVED: {
    message: "Project is already archived",
    code: 400,
    errorCode: "PROJECT_ALREADY_ARCHIVED",
    suggestion: "The project is already archived.",
  },
  UNAUTHORIZED_TO_RESTORE_PROJECT: {
    message: "Unauthorized to restore the project",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_RESTORE_PROJECT",
    suggestion: "Only the product owner can restore the project.",
  },
  INVALID_RESTORE_STATE: {
    message: "Only archived projects can be restored",
    code: 400,
    errorCode: "INVALID_RESTORE_STATE",
    suggestion: "Please archive the project before trying to restore it.",
  },
};
