export const errors = {
  SPRINT_NOT_FOUND: {
    message: "Sprint not found",
    code: 404,
    errorCode: "SPRINT_NOT_FOUND",
    suggestion: "Please check the existence of the sprint.",
  },
  SPRINT_NAME_REQUIRED: {
    message: "Sprint name is required",
    code: 400,
    errorCode: "SPRINT_NAME_REQUIRED",
    suggestion: "Please provide a name for the sprint.",
  },
  SPRINT_START_DATE_REQUIRED: {
    message: "Sprint start date is required",
    code: 400,
    errorCode: "SPRINT_START_DATE_REQUIRED",
    suggestion: "Please provide a start date for the sprint.",
  },
  SPRINT_START_DATE_INVALID: {
    message: "Sprint start date must be within the project duration",
    code: 400,
    errorCode: "SPRINT_START_DATE_INVALID",
    suggestion: "Please provide a valid start date for the sprint.",
  },
  SPRINT_DURATION_REQUIRED: {
    message: "Sprint duration is required",
    code: 400,
    errorCode: "SPRINT_DURATION_REQUIRED",
    suggestion: "Please provide a duration for the sprint.",
  },
  SPRINT_DURATION_INVALID: {
    message: "Sprint duration must be between 1 and 4 weeks",
    code: 400,
    errorCode: "SPRINT_DURATION_INVALID",
    suggestion: "Please provide a valid duration for the sprint (1-4 weeks).",
  },
  SPRINT_OVERLAPPING: {
    message: "Sprint dates overlap with an existing sprint",
    code: 400,
    errorCode: "SPRINT_OVERLAPPING",
    suggestion: "Please choose a different start or end date for the sprint.",
  },
  SPRINT_END_DATE_EXCEEDS_PROJECT_END_DATE: {
    message: "Sprint end date exceeds project end date",
    code: 400,
    errorCode: "SPRINT_END_DATE_EXCEEDS_PROJECT_END_DATE",
    suggestion: "Please choose an end date that is on or before the project end date.",
  },
  UNAUTHORIZED_TO_ACCESS_PROJECT_SPRINTS: {
    message: "Unauthorized to access the sprints of the project",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_ACCESS_PROJECT_SPRINTS",
    suggestion: "You do not have permission to access the sprints of this project.",
  },
  UNAUTHORIZED_TO_ACCESS_SPRINT: {
    message: "Unauthorized to access the sprint",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_ACCESS_SPRINT",
    suggestion: "You do not have permission to access this sprint.",
  },
  UNAUTHORIZED_TO_CREATE_SPRINT: {
    message: "Unauthorized to create a sprint in the project",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_CREATE_SPRINT",
    suggestion: "You do not have permission to create a sprint in this project.",
  },
  UNAUTHORIZED_TO_UPDATE_SPRINT: {
    message: "Unauthorized to update the sprint",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_UPDATE_SPRINT",
    suggestion: "You do not have permission to update this sprint.",
  },
  UNAUTHORIZED_TO_DELETE_SPRINT: {
    message: "Unauthorized to delete the sprint",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_DELETE_SPRINT",
    suggestion: "You do not have permission to delete this sprint.",
  },
  CANNOT_DELETE_ACTIVE_SPRINT: {
    message: "Cannot delete an active sprint",
    code: 400,
    errorCode: "CANNOT_DELETE_ACTIVE_SPRINT",
    suggestion: "Please complete or archive the sprint before deleting it.",
  },
  ANOTHER_ACTIVE_SPRINT_EXISTS: {
    message: "Another active sprint already exists for the project",
    code: 400,
    errorCode: "ANOTHER_ACTIVE_SPRINT_EXISTS",
    suggestion: "Please complete or archive the existing active sprint before creating a new one.",
  },
  UNAUTHORIZED_TO_START_SPRINT: {
    message: "Unauthorized to start the sprint",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_START_SPRINT",
    suggestion: "You do not have permission to start this sprint.",
  },
  SPRINT_ALREADY_STARTED_OR_COMPLETED: {
    message: "Sprint has already been started or completed",
    code: 400,
    errorCode: "SPRINT_ALREADY_STARTED_OR_COMPLETED",
    suggestion: "Please check the status of the sprint before starting it.",
  },
  ACTIVE_SPRINT_ALREADY_EXISTS: {
    message: "An active sprint already exists for the project",
    code: 400,
    errorCode: "ACTIVE_SPRINT_ALREADY_EXISTS",
    suggestion: "Please complete or archive the existing active sprint before starting a new one.",
  },
  UNAUTHORIZED_TO_COMPLETE_SPRINT: {
    message: "Unauthorized to complete the sprint",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_COMPLETE_SPRINT",
    suggestion: "You do not have permission to complete this sprint.",
  },
  SPRINT_NOT_ACTIVE: {
    message: "Sprint is not active",
    code: 400,
    errorCode: "SPRINT_NOT_ACTIVE",
    suggestion: "Only active sprints can be completed. Please start the sprint before completing it.",
  },
};
