export const errors = {
  TASK_NOT_FOUND: {
    message: "Task not found.",
    code: 404,
    errorCode: "TASK_NOT_FOUND",
    suggestion: "Please provide a valid task ID.",
  },
  PARENT_TASK_NOT_FOUND: {
    message: "Parent task not found.",
    code: 404,
    errorCode: "PARENT_TASK_NOT_FOUND",
    suggestion: "Please provide a valid parent task ID for the sub-task.",
  },
  UNAUTHORIZED_TO_ACCESS_PROJECT_TASKS: {
    message: "You are not authorized to access tasks of this project.",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_ACCESS_PROJECT_TASKS",
    suggestion: "You must be a team member, product owner, or admin to access tasks of this project.",
  },
  INVALID_TASK_TYPE: {
    message: "Invalid task type.",
    code: 400,
    errorCode: "INVALID_TASK_TYPE",
    suggestion: "Please provide a valid task type value.",
  },
  INVALID_TASK_STATUS: {
    message: "Invalid task status.",
    code: 400,
    errorCode: "INVALID_TASK_STATUS",
    suggestion: "Please provide a valid task status value.",
  },
  TASK_TITLE_REQUIRED: {
    message: "Task title is required.",
    code: 400,
    errorCode: "TASK_TITLE_REQUIRED",
    suggestion: "Please provide a title for the task.",
  },
  INVALID_STORY_POINTS: {
    message: "Invalid story points value.",
    code: 400,
    errorCode: "INVALID_STORY_POINTS",
    suggestion: "Please provide a valid story points value.",
  },
  INVALID_PRIORITY: {
    message: "Invalid priority value.",
    code: 400,
    errorCode: "INVALID_PRIORITY",
    suggestion: "Please provide a valid priority value.",
  },
  UNAUTHORIZED_TO_ADD_PROJECT_TASKS: {
    message: "You are not authorized to add tasks to this project.",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_ADD_PROJECT_TASKS",
    suggestion: "Only the product owner of the project can add tasks.",
  },
  SUB_TASK_REQUIRES_PARENT: {
    message: "Sub-tasks (And only sub-tasks) must have a parent task.",
    code: 400,
    errorCode: "SUB_TASK_REQUIRES_PARENT",
    suggestion: "Please provide a the task's parent Id for the sub-task.",
  },
  MORE_THAN_ONE_LEVEL_OF_SUBTASKS: {
    message: "Only one level of sub-tasks is allowed.",
    code: 400,
    errorCode: "MORE_THAN_ONE_LEVEL_OF_SUBTASKS",
    suggestion: "Sub-tasks cannot have their own sub-tasks.",
  },
  COMPLETED_SPRINT: {
    message: "Cannot add task to a completed sprint.",
    code: 400,
    errorCode: "COMPLETED_SPRINT",
    suggestion: "Please move the task to a sprint that is not completed.",
  },
  UNAUTHORIZED_TO_UPDATE_PROJECT_TASKS: {
    message: "You are not authorized to update tasks of this project.",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_UPDATE_PROJECT_TASKS",
    suggestion: "Only the product owner of the project can update tasks.",
  },
  UNAUTHORIZED_TO_DELETE_PROJECT_TASKS: {
    message: "You are not authorized to delete tasks of this project.",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_DELETE_PROJECT_TASKS",
    suggestion: "Only the product owner of the project can delete tasks.",
  },
  UNAUTHORIZED_TO_MOVE_PROJECT_TASKS: {
    message: "You are not authorized to move tasks of this project.",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_MOVE_PROJECT_TASKS",
    suggestion: "Only the product owner and team members of the project can move tasks.",
  },
  TASK_WITHOUT_SPRINT: {
    message: "Task must be assigned to a sprint before leaving the product backlog.",
    code: 400,
    errorCode: "TASK_WITHOUT_SPRINT",
    suggestion: "Please assign the task to a sprint before moving it from the product backlog.",
  },
  UNAUTHORIZED_TO_SUBMIT_TASK: {
    message: "You are not authorized to submit this task.",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_SUBMIT_TASK",
    suggestion: "Only the assigned user of the task can submit it.",
  },
  UNAUTHORIZED_TO_UNSUBMIT_TASK: {
    message: "You are not authorized to remove the submission of this task.",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_UNSUBMIT_TASK",
    suggestion: "Only the assigned user of the task can remove its submission.",
  },
  LINK_REQUIRED: {
    message: "Task submission link is required.",
    code: 400,
    errorCode: "LINK_REQUIRED",
    suggestion: "Please provide a link for the task submission.",
  },
  INVALID_SUBMISSION_TYPE: {
    message: "Invalid submission type.",
    code: 400,
    errorCode: "INVALID_SUBMISSION_TYPE",
    suggestion: "Submission type must be either 'file' or 'link'.",
  },
  SUMMARY_REQUIRED: {
    message: "Task submission summary is required.",
    code: 400,
    errorCode: "SUMMARY_REQUIRED",
    suggestion: "Please provide a summary for the task submission.",
  },
  INVALID_COMPLETION_RATE: {
    message: "Invalid completion rate value.",
    code: 400,
    errorCode: "INVALID_COMPLETION_RATE",
    suggestion: "Please provide a valid completion rate value between 0 and 100.",
  },
  INVALID_HOURS_SPENT: {
    message: "Invalid hours spent value.",
    code: 400,
    errorCode: "INVALID_HOURS_SPENT",
    suggestion: "Please provide a valid hours spent value.",
  },
  TASK_NOT_IN_PROGRESS_OR_REVIEW: {
    message: "Task must be in 'In Progress' or 'Review' status to be submitted.",
    code: 400,
    errorCode: "TASK_NOT_IN_PROGRESS_OR_REVIEW",
    suggestion: "Please move the task to 'In Progress' or 'Review' status before submitting.",
  },
  NO_SUBMISSION_TO_DELETE: {
    message: "There is no submission to delete for this task.",
    code: 400,
    errorCode: "NO_SUBMISSION_TO_DELETE",
    suggestion: "This task does not have a submission to remove.",
  },
  ASSIGNED_TEAM_MEMBER_REQUIRED: {
    message: "Assigned team member is required.",
    code: 400,
    errorCode: "ASSIGNED_TEAM_MEMBER_REQUIRED",
    suggestion: "Please provide a user ID to assign the task to.",
  },
  INVALID_REVIEW_ACTION: {
    message: "Invalid review action.",
    code: 400,
    errorCode: "INVALID_REVIEW_ACTION",
    suggestion: "Review action must be either 'approve' or 'reject'.",
  },
  TASK_NOT_IN_REVIEW: {
    message: "Task must be in 'Review' status to be reviewed.",
    code: 400,
    errorCode: "TASK_NOT_IN_REVIEW",
    suggestion: "Please move the task to 'Review' status before reviewing.",
  },
  NO_TASK_SUBMISSION_FOUND: {
    message: "There is no submission for this task.",
    code: 400,
    errorCode: "NO_TASK_SUBMISSION_FOUND",
    suggestion: "The task must have a submission before it can be viewed or reviewed.", 
  },
  UNAUTHORIZED_TO_REVIEW_TASKS: {
    message: "You are not authorized to review tasks of this project.",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_REVIEW_TASKS",
    suggestion: "Only the product owner of the project can review tasks.",
  },
  UNAUTHORIZED_TO_VIEW_SUBMISSION: {
    message: "You are not authorized to view the submission of this task.",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_VIEW_SUBMISSION",
    suggestion: "Only the assigned user, product owner, and team members of the project can view the task submission.",
  },
  UNAUTHORIZED_TO_DOWNLOAD_SUBMISSION: {
    message: "You are not authorized to download the submission of this task.",
    code: 403,
    errorCode: "UNAUTHORIZED_TO_DOWNLOAD_SUBMISSION",
    suggestion: "Only the assigned user, product owner, and team members of the project can download the task submission.",
  },
};
